### ISSUE TITLE
SDK 3.5.0 not working on iOS8

### ISSUE THREAD

**Issue by gaurangtalwadkar** [Kochava/kochava-tracker-ios-sdk-cocoapod#10]
Environment:
iOS 8
SDK 3.5.0

Getting exception `Tracker LogMessage Exception (Caught)` on configuration with app id.

**Comment by johnbushnell** [comment]
Is that 8.0, and do you know if the same is true with 8.1 or higher?

**Comment by johnbushnell** [comment]
Also, can you confirm that message.  Is that "Kochava LogMessage Exception (Caught)" as opposed to "Tracker"?  There should also be a UUID associated with that message and perhaps a detail of the exception it caught.  What you're describing appears to be a backup mechanism to catch exceptions which does not actually result in a crash.  Did that result in an actual crash or simply a log message?

**Comment by gaurangtalwadkar** [comment]
It's happening on iOS 8.x. Yes I'm getting message like 'Tracker LogMessage Exception (Caught) - xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'. But doesn't crash the app, just showing the exception message.

**Comment by johnbushnell** [comment]
The problem you're experiencing occurs in a handful of integrations, and as of yet we don't know what makes those environments different from the norm.  We released version 3.5.1 last Friday.  It moves to a new compiler version, and there were some other provisions to attempt to guard against this issue.  It would be helpful to give this version a try.  If the condition goes away we'd like to know.  If it remains it may change how it manifests itself, and that would be good to know as well.

**Comment by johnbushnell** [comment]
By any chance, do you know if your app makes use of takeRetainedValue or takeUnretainedValue?  We've been able to trigger a similar error by using these methods in the wrong way.  I know you can't speak to private SDKs, but maybe you are using them.

**Comment by gaurangtalwadkar** [comment]
Tried new version 3.5.1. But the issue still happening. Giving error on configure. Checked our code, we are not using takeRetainedValue or takeUnretainedValue anywhere.

**Comment by johnbushnell** [comment]
I'd like to get you connected with our full support team going forward so that we can work directly with you on this. Please email support@kochava.com with your app id and a link to this issue and we'll get to work on this immediately.
